### ISSUE TITLE
Please provide example to encrypt query pareters

### ISSUE THREAD

**Issue by munish-dhiman** [awslabs/aws-dynamodb-encryption-java#17]
I am not able to fetch data using query parameters as the data i am passing is not encrypted one.

Thanks

**Comment by SalusaSecondus** [comment]
I don't understand the request. Are you asking for the ability to encrypt the Hash/Range key or secondary indices?

While this is a commonly requested feature, it requires something called property preserving encryption (or deterministic encryption depending on the field) and is very challenging to get right and even more challenging to use safely. Since I've been unable so far to figure out how to do this is a way which does not make it extremely easy for people to misuse, I am not prioritizing this feature.  (One of the principals of this library is that is must be difficult to misuse.)

My standard advice in this case is to figure out how to not query on sensitive attributes if at all possible.

**Comment by munish-dhiman** [comment]
May be you are right we should in filter data on the basis of encrypted attributes.

Thanx for reply.
