### ISSUE TITLE
Scans/queries with projections are not supported

### ISSUE THREAD

**Issue by francesco-russo** [awslabs/aws-dynamodb-encryption-java#7]
Hi there,
Using this library I have realised, please correct me if I am wrong, that projections are not supported.

*How-to Reproduce it*
How to reproduce the issue:
```
/*
YourModelClass has fields:
- hashKey (@DoNotTouch)
- attributeA (@DoNotTouch)
- attributeB 
*/
String PROJECTION = "hashKey, attributeA";
DynamoDBMapper mapper = ...
PaginatedScanList<ConfigurationEntry> paginatedScanList = mapper.scan(
                YourModelClass.class,
                new DynamoDBScanExpression().
                        withProjectionExpression(PROJECTION),
                mapperConfig
        );
```

*Analysis*
The scan above fails because:
-  the special attribute named ```*amzn-ddb-map-desc*``` is not part of the projection hence is not loaded
- ```DynamoDBEncryptor.decryptRecord(...)``` produces an empty ```materialDescription``` (line 238 evaluates to ```false```)
- ```DirectKmsMaterialProvider.getDecryptionMaterials(...)``` throws NPE (line 121) because it tries to wrap a ```null``` reference:
```
ByteBuffer.wrap(Base64.decode(materialDescription.get(ENVELOPE_KEY)))
```

*Workarounds? Hacks?*
As a hack I've tried to add those special ```amz...``` attributes in my projection, but it fails because those are "reserved" attributes, so there is no way apparently on my side to work around the issue.

I'm not even sure if you can do anything, since the encryption/decryption only happens, respectively, before the standard Dynamo client puts the data to Dynamo, after the data has been loaded from Dynamo.

If only those attributes were not using reserved names though... Would it be a security risk to "expose" them to the end-user for cases like this? After all the key is already secured in KMS or similar.
If the concern then is that an attacker might compromise those attributes well, if the attacker is already there it might as well be able to compromise the items anyway, am I right?

**Comment by david-at-aws** [comment]
It's theoretically possible, but in practice is going to be pretty tricky.

First: those attributes are "reserved" because of DynamoDB's expression syntax. You can include them in the projection expression by [substituting them](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ExpressionPlaceholders.html) using the ExpressionAttributeNames map. There's no security risk if an attacker who doesn't have access to your KMS key sees them.

```java
new DynamoDBScanExpression()
    .withProjectionExpression("hashKey, attributeA, #mapdesc, #mapsig, ...")
    .addExpressionAttributeNamesEntry("#mapdesc", "*amzn-ddb-map-desc*")
    .addExpressionAttributeNamesEntry("#mapsig", "*amzn-ddb-map-sig*")
    ...
```

(see [this code](https://github.com/awslabs/aws-dynamodb-encryption-java/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptor.java#L54) for the full set of encryption-related attributes you'll need to project out)

Secondly, and more importantly: the encryption client calculates a signature over any attributes that are not annotated with `@DoNotTouch` on writes, and verifies this signature on reads. You'll need to project out all of the attributes that were used to calculate the signature, or you'll get a signature "mismatch"; in your case, the reader will calculate a signature for the empty string (since you haven't projected attributeB), but the signature stored on the item will be for whatever attributeB's value is.

In your example you're only projecting out attributes that are not encrypted/signed, so there's an easy solution: do the scan using a "normal" DynamoDBMapper that doesn't even try to decrypt/verify the signature. That obviously doesn't generalize very well though. :)

**Comment by SalusaSecondus** [comment]
david-at-aws is completely correct. One additional note, *not* signing your hashkey is usually a security bug as it permits attackers to copy data from one record to another in an undetected manner.

So long as you are not worried about verifying the signature, you can project any non-encrypted attributes, just be sure to not pass it through the encryption client.

**Comment by francesco-russo** [comment]
Cool david, I'll apply the "addExpressionAttributeNamesEntry" for we do have cases in which need to retrieve only the ciphered attribute.
Thanks for the prompt reply.

PS: the two scenarios you have discussed might be useful to others too, so probably you'd consider updating the docs with that?
